<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
		<UserSecretsId>cbdadc72-0914-4dd0-928d-5f374af9c526</UserSecretsId>
		<MinVerTagPrefix>v</MinVerTagPrefix>
		<MinVerDefaultPreReleaseIdentifiers>staging.0</MinVerDefaultPreReleaseIdentifiers>
		<!-- Remove after the v1.0.0 tag is created. -->
		<MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Markdig" />
		<PackageReference Include="MinVer">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MudBlazor" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\Application\SoloDevBoard.Application\SoloDevBoard.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SoloDevBoard.Infrastructure\SoloDevBoard.Infrastructure.csproj" />
    <ProjectReference Include="..\..\SoloDevBoard.ServiceDefaults\SoloDevBoard.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
